- header:
    model: sn5600
    nvue-api-version: nvue_v1
    rev-id: 1.0
    version: Cumulus Linux 5.11.5
- set:
    interface:
      eth0:
        ip:
          address:
            172.31.17.23/21: {}
          gateway:
            172.31.16.254: {}
          vrf: mgmt
        link:
          mtu: 1500
        type: eth
      lo:
        ip:
          address:
            10.255.0.13/32: {}
        type: loopback
      swp1-5,8-12:
        link:
          breakout:
            2x: {}
      swp1-5,8-12,33-64,swp10s0-1,swp11s0-1,swp12s0-1,swp1s0-1,swp2s0-1,swp3s0-1,swp4s0-1,swp5s0-1,swp8s0-1,swp9s0-1:
        type: swp
      swp1s0:
        ip:
          address:
            10.200.57.2/31: {}
      swp1s1:
        ip:
          address:
            10.200.57.0/31: {}
      swp2s0:
        ip:
          address:
            10.200.56.2/31: {}
      swp2s1:
        ip:
          address:
            10.200.56.0/31: {}
      swp3s0:
        ip:
          address:
            10.200.53.2/31: {}
      swp3s1:
        ip:
          address:
            10.200.53.0/31: {}
      swp4s0:
        ip:
          address:
            10.200.52.2/31: {}
      swp4s1:
        ip:
          address:
            10.200.52.0/31: {}
      swp5s0:
        ip:
          address:
            10.200.49.2/31: {}
      swp5s1:
        ip:
          address:
            10.200.49.0/31: {}
      swp8s0:
        ip:
          address:
            10.200.58.2/31: {}
      swp8s1:
        ip:
          address:
            10.200.58.0/31: {}
      swp9s0:
        ip:
          address:
            10.200.55.2/31: {}
      swp9s1:
        ip:
          address:
            10.200.55.0/31: {}
      swp10s0:
        ip:
          address:
            10.200.54.2/31: {}
      swp10s0-1,swp11s0-1,swp12s0-1,swp1s0-1,swp2s0-1,swp3s0-1,swp4s0-1,swp5s0-1,swp8s0-1,swp9s0-1:
        link:
          fec: auto
      swp10s0-1,swp11s0-1,swp12s0-1,swp1s0-1,swp2s0-1,swp33-64,swp3s0-1,swp4s0-1,swp5s0-1,swp8s0-1,swp9s0-1:
        ip:
          ipv4:
            forward: on
        link:
          mtu: 9216
          state:
            up: {}
      swp10s1:
        ip:
          address:
            10.200.54.0/31: {}
      swp11s0:
        ip:
          address:
            10.200.51.2/31: {}
      swp11s1:
        ip:
          address:
            10.200.51.0/31: {}
      swp12s0:
        ip:
          address:
            10.200.50.2/31: {}
      swp12s1:
        ip:
          address:
            10.200.50.0/31: {}
      swp33:
        ip:
          address:
            10.254.0.129/31: {}
      swp33-64:
        ip:
          ipv6:
            enable: on
            forward: on
          neighbor-discovery:
            router-advertisement:
              enable: on
        link:
          auto-negotiate: on
          speed: auto
      swp34:
        ip:
          address:
            10.254.0.131/31: {}
      swp35:
        ip:
          address:
            10.254.0.133/31: {}
      swp36:
        ip:
          address:
            10.254.0.135/31: {}
      swp37:
        ip:
          address:
            10.254.0.137/31: {}
      swp38:
        ip:
          address:
            10.254.0.139/31: {}
      swp39:
        ip:
          address:
            10.254.0.141/31: {}
      swp40:
        ip:
          address:
            10.254.0.143/31: {}
      swp41:
        ip:
          address:
            10.254.0.145/31: {}
      swp42:
        ip:
          address:
            10.254.0.147/31: {}
      swp43:
        ip:
          address:
            10.254.0.149/31: {}
      swp44:
        ip:
          address:
            10.254.0.151/31: {}
      swp45:
        ip:
          address:
            10.254.0.153/31: {}
      swp46:
        ip:
          address:
            10.254.0.155/31: {}
      swp47:
        ip:
          address:
            10.254.0.157/31: {}
      swp48:
        ip:
          address:
            10.254.0.159/31: {}
      swp49:
        ip:
          address:
            10.254.0.161/31: {}
      swp50:
        ip:
          address:
            10.254.0.163/31: {}
      swp51:
        ip:
          address:
            10.254.0.165/31: {}
      swp52:
        ip:
          address:
            10.254.0.167/31: {}
      swp53:
        ip:
          address:
            10.254.0.169/31: {}
      swp54:
        ip:
          address:
            10.254.0.171/31: {}
      swp55:
        ip:
          address:
            10.254.0.173/31: {}
      swp56:
        ip:
          address:
            10.254.0.175/31: {}
      swp57:
        ip:
          address:
            10.254.0.177/31: {}
      swp58:
        ip:
          address:
            10.254.0.179/31: {}
      swp59:
        ip:
          address:
            10.254.0.181/31: {}
      swp60:
        ip:
          address:
            10.254.0.183/31: {}
      swp61:
        ip:
          address:
            10.254.0.185/31: {}
      swp62:
        ip:
          address:
            10.254.0.187/31: {}
      swp63:
        ip:
          address:
            10.254.0.189/31: {}
      swp64:
        ip:
          address:
            10.254.0.191/31: {}
    qos:
      roce:
        enable: on
        mode: lossless
    router:
      bgp:
        autonomous-system: 65103
        enable: on
        router-id: 10.255.0.13
    service:
      ntp:
        mgmt:
          server:
            0.cumulusnetworks.pool.ntp.org: {}
            1.cumulusnetworks.pool.ntp.org: {}
            2.cumulusnetworks.pool.ntp.org: {}
            3.cumulusnetworks.pool.ntp.org: {}
    system:
      aaa:
        class:
          nvapply:
            action: allow
            command-path:
              /:
                permission: all
          nvshow:
            action: allow
            command-path:
              /:
                permission: ro
          sudo:
            action: allow
            command-path:
              /:
                permission: all
        role:
          nvue-admin:
            class:
              nvapply: {}
          nvue-monitor:
            class:
              nvshow: {}
          system-admin:
            class:
              nvapply: {}
              sudo: {}
        user:
          cumulus:
            full-name: cumulus,,,
            # REDACTED sensitive configuration entry
            role: system-admin
      api:
        state: enabled
      config:
        auto-save:
          state: enabled
      control-plane:
        acl:
          acl-default-dos:
            inbound: {}
          acl-default-whitelist:
            inbound: {}
      hostname: leaf-03
      reboot:
        mode: cold
      ssh-server:
        state: enabled
      wjh:
        channel:
          forwarding:
            trigger:
              l2: {}
              l3: {}
              tunnel: {}
        enable: on
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                multipaths:
                  ebgp: 64
                network:
                  10.200.49.0/31: {}
                  10.200.49.2/31: {}
                  10.200.50.0/31: {}
                  10.200.50.2/31: {}
                  10.200.51.0/31: {}
                  10.200.51.2/31: {}
                  10.200.52.0/31: {}
                  10.200.52.2/31: {}
                  10.200.53.0/31: {}
                  10.200.53.2/31: {}
                  10.200.54.0/31: {}
                  10.200.54.2/31: {}
                  10.200.55.0/31: {}
                  10.200.55.2/31: {}
                  10.200.56.0/31: {}
                  10.200.56.2/31: {}
                  10.200.57.0/31: {}
                  10.200.57.2/31: {}
                  10.200.58.0/31: {}
                  10.200.58.2/31: {}
                  10.255.0.13/32: {}
            enable: on
            neighbor:
              10.254.0.128:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.130:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.132:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.134:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.136:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.138:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.140:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.142:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.144:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.146:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.148:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.150:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.152:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.154:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.156:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.158:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.160:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.162:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.164:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.166:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.168:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.170:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.172:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.174:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.176:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.178:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.180:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.182:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.184:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.186:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.188:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
              10.254.0.190:
                address-family:
                  ipv4-unicast:
                    enable: on
                enable: on
                remote-as: 65200
                type: numbered
